const jobData = [
    {
      id: 1,
      title: "Front end developer",
      company: "ABC Tech",
      location: "Bengaluru",
      description: "We are looking for a skilled Front end developer...",
      salary: "$100,000 - $120,000",
      Type: "ENG",
     
    },
    {
        id: 2,
        title: "Front end developer",
        company: "BBC Tech",
        location: "Mumbai",
        description: "We are looking for a skilled Front end developer...",
        salary: "$100,000 - $120,000",
        Type: "ENG",
      },
      {
        id: 3,
        title: "Front end developer",
        company: "LTT Tech",
        location: "Bengaluru",
        description: "We are looking for a skilled Front end developer...",
        salary: "$100,000 - $120,000",
        Type: "ENG",
      },
    {
      id: 4,
      title: "Web Developer",
      company: "XYZ Solutions",
      location: "Bengaluru",
      description: "Join our team as a web developer...",
      salary: "$90,000 - $110,000",
     Type: "ENG",
    },
    {
        id: 5,
        title: "Web Developer",
        company: "LTT Solutions",
        location: "Bengaluru",
        description: "Join our team as a web developer...",
        salary: "$90,000 - $110,000",
       Type: "ENG",
      },
      {
        id: 6,
        title: "Web Developer",
        company: "ABC Tech",
        location: "Mumbai",
        description: "Join our team as a web developer...",
        salary: "$90,000 - $110,000",
        Type: "ENG ",
      },
      {
        id: 7,
        title: "Talent Acquistition",
        company: "ABC Tech",
        location: "Mumbai",
        description: "Join our team as a Talent Acquistition...",
        salary: "$90,000 - $110,000",
        Type:"MAN",
      },
      {
        id: 8,
        title: "Talent Acquistition",
        company: "BBC Tech",
        location: "Mumbai",
        description: "Join our team as a Talent Acquistition...",
        salary: "$90,000 - $110,000",
        Type:"MAN",
      },
      {
        id: 9,
        title: "Talent Acquistition",
        company: "BBC Tech",
        location: "Bengaluru",
        description: "Join our team as a Talent Acquistition...",
        salary: "$90,000 - $110,000",
        Type:"MAN",
      },
      {
        id: 10,
        title: "Talent Acquistition",
        company: "ABC Tech",
        location: "Bengalurui",
        description: "Join our team as a Talent Acquistition...",
        salary: "$90,000 - $110,000",
        Type:"MAN",
      },
      {
        id: 11,
        title: "Talent Acquistition",
        company: "BBC Tech",
        location: "Bengaluru",
        description: "Join our team as a Talent Acquistition...",
        salary: "$90,000 - $110,000",
        Type:"MAN",
      },
      {
        id: 12,
        title: "Digital Marketing",
        company: "BBC Tech",
        location: "Bengaluru",
        description: "Join our team as a Digital Mareketing...",
        salary: "$90,000 - $110,000",
        Type : "DI",
      },
      {
        id: 13,
        title: "Dital Marketing",
        company: "ABC Tech",
        location: "Mumbai",
        description: "Join our team as a Digital Mareketing...",
        salary: "$90,000 - $110,000",
        Type : "DI",
      },
      
    {
      id: 14,
      title: "Digital Marketing",
      company: "BBC Tech",
      location: "Mumbai",
      description: "Join our team as a Digital Mareketing...",
      salary: "$90,000 - $110,000",
      Type : "DI",
    },
    {
      id: 15,
      title: "Digital Marketing",
      company: "ABC Tech",
      location: "Bengaluru",
      description: "Join our team as a Digital Mareketing...",
      salary: "$90,000 - $110,000",
      Type : "DI",
    }
  ];
  
  export default jobData